### ISSUE TITLE
[Bug] use one sticky queue per worker process

### ISSUE THREAD

**Issue by yiminc** [temporalio/sdk-core#224]
Both sdk-go and sdk-java uses one sticky task queue per worker process.
Currently core uses one sticky queue per one named task queue per process.
There are uses cases where one worker process would poll from hundreds of task queues and it would be 100x more expensive on server.
A simple bookkeeping would be needed on sdk if a proper concurrent and RPS control is needed per named task queue.

**Comment by Sushisource** [comment]
@yiminc I thought we hadn't decided if this needed to be changed SDK side. Ideally server could support this as @mmcshane  mentioned. It's not actually possible to accurately constrain maximum concurrent WFTs per queue without this.

Example:

Worker listens on `q1` and `q2`. It also listens on `w` (it's sticky queue). It has chosen to limit max WFTs for both `q1` and `q2` to `1`. 

1. It gets a task for `q1`, which is now at the limit.
2. It needs to keep listening to `w` because maybe a sticky task for `q2` will come there, and `q2` has an open slot
3. Oops, `w` delivers a task for `q1`

Hence the impossibility. Now, maybe temporarily violating the max isn't really such a big deal, but ideally we can accurately constrain the limit here. When I originally did this the server team said it ought to be OK.

If not, we can go back to one sticky queue, but we will need to be clear that the max concurrent limits are more like suggestions in that case.

**Comment by mfateev** [comment]
What is the use case for a worker to poll on hundreds of workflow task queues?

**Comment by Sushisource** [comment]
I'm closing this in favor of https://github.com/temporalio/sdk-core/issues/227 since we discussed the real need here is actually for many activity queues.
