### ISSUE TITLE
Rust SDK

### ISSUE THREAD

**Issue by lcmgh** [temporalio/sdk-core#380]
Are there plans for a Rust SDK with same features as the Typescript one?

**Comment by Sushisource** [comment]
@lcmgh There are no immediate plans to dedicate resources to releasing. One exists in this repo, but the API has no stability guarantees. It works though, since it's using the same basis as TypeScript and Python.

I'd love to release it, but it's just a matter of priorities for us :)

Closing this issue - but feel free to get in touch on our community slack or forums. I'm always happy to hear feedback or questions.
