### ISSUE TITLE
[Bug] Changing activity type name should result in non deterministic error

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-core#443]
The following change should result in non deterministic error:

```diff
const activities = proxyActivities({ startToCloseTimeout: '1m' })
export async function myWorkflow(): Promise<void> {
-  await activities.foo();
+  await activities.bar();
}
```

Today, the workflow can be replayed and no error is emitted.

**Comment by mjameswh** [comment]
Validating activity type name would also help detect many cases where significant changes to workflow code structure does not result in non-determinism error on replay because former history events get perniciously matched to totally unrelated commands in the new code.

I have seen this situation myself a few time, but here is a very interesting example submitted by a slack user. He starts a workflow execution using this code, then, while the workflow is waiting on the final `sleep` (at `E`), he stops the worker, and modifies `parseWebhook` from being a workflow function to being an activity (ie. comment line `B` and uncomment line `C`), _without using a patch_ (the user was actually trying to figure out if a patch was needed in that case), and restarts the worker to test.

The user gets no non-determinism error, but he's puzzled observing that the workflow is now stuck _inside_ the main loop. Turns out that the newly added activity at line `C` is incorrectly matched with the historical execution of activity at line `D`. `webhookType` is now `undefined`, so the code takes the `continue` statement, and the implicit `sleep` done by the condition at line `A` now get incorrectly matched to the `sleep` at line `E`.

```
export async function testWorkflow(): Promise<void> {
  let status = 'pending';
  let webhook: object | null = null;
  let webhookType;

  setHandler(webhookSignal, (wbh: object) => {
    webhook = wbh;
  });

  while(!isFinalStatus(status)) {
    if (await condition(() => webhook !== null, WEBHOOK_TIMEOUT)) {       // *A*
      // Before
      ({ status, webhookType } = parseWebhook(webhook));                  // *B*

      // After
      // ({ status, webhookType } = await coreAct.parseWebhook(webhook)); // *C*

      webhook = null;
      if (webhookType !== 'test') continue;
    } else {
      status = await coreAct.getTransactionStatus();
    }

    await coreAct.updateTransaction({ status });                          // *D*
  }

  await sleep(120 * 1000);                                                // *E*
}
```

**Comment by jcm300** [comment]
Slack user here 👋 
If somehow there's the need of the full code example, I can provide it.

**Comment by Sushisource** [comment]
This always should have been considered nondeterminism. Surprised this one slipped by somehow. I'll fix shortly.

**Comment by bergundy** [comment]
Will be addressed in this issue https://github.com/temporalio/sdk-core/issues/443.

**Comment by Sushisource** [comment]
@bergundy Lol what you just linked this issue to itself

**Comment by bergundy** [comment]
🤦

**Comment by bergundy** [comment]
For some reason I thought this conversation was in the TS SDK issues...
