### ISSUE TITLE
[Feature Request] Don't use `derive_builder`

### ISSUE THREAD

**Issue by lucperkins** [temporalio/sdk-core#648]
### Is your feature request related to a problem? Please describe.

In general, "magical" libs like `derive_builder` are nice for speedy development of complex structs but they have the important downside that they don't play nicely with IDEs.

### Describe the solution you'd like

Just plain old structs using a builder pattern.

### Additional context

N/A

I'm happy to do this work myself if others agree that this is a better path.

**Comment by Sushisource** [comment]
Thanks for the input! I'm inclined not to avoid useful language features and libraries due to IDE deficiencies. The generated code from these macros works just fine with IntelilJ IDEs for example, so it's clearly possible. I think this is mostly a matter of (I'm assuming) rust-analyzer catching up to being able to handle these.

It's something I'll consider once we start actually productionizing the Rust SDK, but for now I don't want to replace these with buckets of hand-written builders.
